spring:
  application:
    name: flow-manager
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/flow_manager
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flow-manager-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

minio:
  endpoint: http://localhost:9000
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: conversions
  bucket-name: conversions
server:
  tomcat:
    connection-timeout: 5000